image: rust:1.37.0-stretch

cache:
  paths:
    - $HOME/.cargo/

before_script:
  - cargo install mdbook

test:
  stage: test
  script:
    - echo No Test Specified || false
  only:
    - branches
  except:
    - master

pages:
  stage: deploy
  script:
    - mdbook build
  artifacts:
    paths:
      - book
    expire_in: 1 week
  only:
    - master
